import { BusinessPreset, Customer, FollowUp, Job, ModuleConfig, Note, Payment, Task, WorkspaceConfig } from './types';

export const BUSINESS_PRESETS: BusinessPreset[] = [
  {
    id: 'cleaning',
    name: 'Cleaning Company',
    icon: 'Sparkles',
    defaultSoftware: 'HubSpot & Jobber',
    recommendedModules: ['customers', 'jobs', 'tasks', 'notes', 'followups', 'payments'],
    moduleLabels: {
      customers: 'Clients',
      jobs: 'Cleaning Jobs',
      tasks: 'Checklists',
      notes: 'Site Notes',
      followups: 'Re-bookings',
      payments: 'Invoices',
    },
    sampleName: 'Bright & Shine Cleaners',
  },
  {
    id: 'gardening',
    name: 'Gardener / Landscaper',
    icon: 'Trees',
    defaultSoftware: 'Salesforce & Excel',
    recommendedModules: ['customers', 'jobs', 'tasks', 'followups', 'payments'],
    moduleLabels: {
      customers: 'Properties',
      jobs: 'Garden Visits',
      tasks: 'Season Checklist',
      notes: 'Plant Notes',
      followups: 'Season Follow-ups',
      payments: 'Payments',
    },
    sampleName: 'Oakwood Garden Care',
  },
  {
    id: 'window_cleaning',
    name: 'Window Cleaner',
    icon: 'Sun',
    defaultSoftware: 'Squeegee / Monday',
    recommendedModules: ['customers', 'jobs', 'followups', 'payments'],
    moduleLabels: {
      customers: 'Round List',
      jobs: 'Cleans',
      tasks: 'Prep Tasks',
      notes: 'Access Notes',
      followups: '4-Week Reminders',
      payments: 'Collections',
    },
    sampleName: 'ClearView Window Cleaning',
  },
  {
    id: 'photography',
    name: 'Photographer',
    icon: 'Camera',
    defaultSoftware: 'HoneyBook & Dubsado',
    recommendedModules: ['customers', 'jobs', 'tasks', 'notes', 'payments'],
    moduleLabels: {
      customers: 'Clients',
      jobs: 'Shoots',
      tasks: 'Editing Tasks',
      notes: 'Shot Lists',
      followups: 'Inquiries',
      payments: 'Deposits & Invoices',
    },
    sampleName: 'Aura Studio UK',
  },
  {
    id: 'dog_grooming',
    name: 'Dog Groomer / Pet Care',
    icon: 'Dog',
    defaultSoftware: 'Zoho Books',
    recommendedModules: ['customers', 'jobs', 'notes', 'followups', 'payments'],
    moduleLabels: {
      customers: 'Pet Parents',
      jobs: 'Grooming Sessions',
      tasks: 'Daily Prep',
      notes: 'Coat & Temperament',
      followups: 'Groom Reminders',
      payments: 'Payments',
    },
    sampleName: 'Paws & Coats Grooming',
  },
  {
    id: 'repair',
    name: 'Trades / Repair / Handyman',
    icon: 'Wrench',
    defaultSoftware: 'ClickUp & QuickBooks',
    recommendedModules: ['customers', 'jobs', 'tasks', 'notes', 'payments'],
    moduleLabels: {
      customers: 'Homeowners',
      jobs: 'Repair Callouts',
      tasks: 'Parts Needed',
      notes: 'Job Photos & Notes',
      followups: 'Quote Follow-ups',
      payments: 'Invoices',
    },
    sampleName: 'Apex Property Maintenance',
  },
  {
    id: 'consultant',
    name: 'Consultant / Freelancer',
    icon: 'Briefcase',
    defaultSoftware: 'HubSpot & Asana',
    recommendedModules: ['customers', 'jobs', 'tasks', 'notes', 'payments'],
    moduleLabels: {
      customers: 'Accounts',
      jobs: 'Projects',
      tasks: 'Deliverables',
      notes: 'Meeting Minutes',
      followups: 'Proposals',
      payments: 'Invoices',
    },
    sampleName: 'Vanguard Strategy UK',
  },
];

export const DEFAULT_MODULES: ModuleConfig[] = [
  {
    id: 'customers',
    enabled: true,
    label: 'Customers',
    defaultLabel: 'Customers',
    iconName: 'Users',
    description: 'Keep contact info, addresses, and history in one place.',
  },
  {
    id: 'jobs',
    enabled: true,
    label: 'Jobs',
    defaultLabel: 'Jobs',
    iconName: 'Briefcase',
    description: 'Schedule and track upcoming visits or projects.',
  },
  {
    id: 'tasks',
    enabled: true,
    label: 'Tasks',
    defaultLabel: 'Tasks',
    iconName: 'CheckSquare',
    description: 'Simple checkable to-do items for your team.',
  },
  {
    id: 'notes',
    enabled: true,
    label: 'Notes',
    defaultLabel: 'Notes',
    iconName: 'FileText',
    description: 'Quick site notes, gate codes, or client preferences.',
  },
  {
    id: 'followups',
    enabled: true,
    label: 'Follow-ups',
    defaultLabel: 'Follow-ups',
    iconName: 'Clock',
    description: 'Never forget a repeat booking, quote check, or phone call.',
  },
  {
    id: 'payments',
    enabled: true,
    label: 'Payments',
    defaultLabel: 'Payments',
    iconName: 'Receipt',
    description: 'Track paid, pending, and overdue balances.',
  },
];

export const DEFAULT_WORKSPACE: WorkspaceConfig = {
  businessName: 'Bright & Clean Services',
  businessType: 'Cleaning Company',
  replaceSoftware: 'HubSpot & Jobber',
  accentColor: '#FF5722', // Bold Typography Accent (Orange)
  modules: DEFAULT_MODULES,
  isConfigured: false,
  createdAt: new Date().toISOString(),
};

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Sarah Jenkins',
    company: 'The Oakwood Bistro',
    email: 'sarah@oakwoodbistro.co.uk',
    phone: '07700 900123',
    status: 'active',
    tags: ['Commercial', 'Weekly'],
    notes: 'Key code for back entry: 4819. Clean before 8:30 AM on Tuesdays.',
    createdAt: '2026-08-10',
  },
  {
    id: 'cust-2',
    name: 'David Miller',
    company: 'Miller & Co Law',
    email: 'david.m@millerlaw.co.uk',
    phone: '07700 900456',
    status: 'active',
    tags: ['Office', 'Fortnightly'],
    notes: 'Requires invoice on 1st of every month.',
    createdAt: '2026-08-14',
  },
  {
    id: 'cust-3',
    name: 'Emma Watson',
    company: '',
    email: 'emma.w@gmail.com',
    phone: '07700 900789',
    status: 'lead',
    tags: ['Residential', 'Deep Clean'],
    notes: 'Requested quote for 4-bedroom house move-out clean.',
    createdAt: '2026-08-28',
  },
  {
    id: 'cust-4',
    name: 'James Thorn',
    company: 'Thorn Architect Studio',
    email: 'j.thorn@thornarch.co.uk',
    phone: '07700 900234',
    status: 'active',
    tags: ['Commercial', 'Monthly'],
    notes: 'Prefers eco-friendly cleaning supplies only.',
    createdAt: '2026-07-15',
  },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-1',
    title: 'Weekly Commercial Clean',
    customerId: 'cust-1',
    status: 'scheduled',
    date: '2026-09-03',
    amount: 140,
    notes: 'Focus on main dining area and kitchen floors.',
  },
  {
    id: 'job-2',
    title: 'Fortnightly Office Clean',
    customerId: 'cust-2',
    status: 'scheduled',
    date: '2026-09-04',
    amount: 195,
    notes: 'Sanitise all meeting room desks and empty recycle bins.',
  },
  {
    id: 'job-3',
    title: 'Move-out Deep Clean',
    customerId: 'cust-3',
    status: 'in_progress',
    date: '2026-09-02',
    amount: 280,
    notes: 'Oven clean included. Check oven racks.',
  },
  {
    id: 'job-4',
    title: 'Studio Carpet & Floor Care',
    customerId: 'cust-4',
    status: 'completed',
    date: '2026-08-29',
    amount: 320,
    notes: 'Completed in 3.5 hours. Customer very happy.',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Order extra microfiber cloths & floor cleaner',
    dueDate: '2026-09-03',
    completed: false,
    priority: 'high',
  },
  {
    id: 'task-2',
    title: 'Confirm key handover with Sarah for Tuesday',
    customerId: 'cust-1',
    jobId: 'job-1',
    dueDate: '2026-09-02',
    completed: true,
    priority: 'medium',
  },
  {
    id: 'task-3',
    title: 'Prepare oven cleaning chemical kit for Emma',
    customerId: 'cust-3',
    jobId: 'job-3',
    dueDate: '2026-09-02',
    completed: false,
    priority: 'high',
  },
  {
    id: 'task-4',
    title: 'Send monthly feedback survey to David Miller',
    customerId: 'cust-2',
    dueDate: '2026-09-05',
    completed: false,
    priority: 'low',
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: 'note-1',
    title: 'Oakwood Bistro Entry Code',
    content: 'Key safe code is 4819 at side entry door. Alarm pin code is 9102.',
    customerId: 'cust-1',
    tags: ['Access', 'Key Code'],
    createdAt: '2026-08-10',
    updatedAt: '2026-08-10',
  },
  {
    id: 'note-2',
    title: 'Eco Supply Preferences - Thorn Arch',
    content: 'Do not use bleach products anywhere in studio. Use citrus-based eco spray only.',
    customerId: 'cust-4',
    tags: ['Supplies', 'Preference'],
    createdAt: '2026-08-15',
    updatedAt: '2026-08-15',
  },
];

export const INITIAL_FOLLOWUPS: FollowUp[] = [
  {
    id: 'fol-1',
    customerId: 'cust-3',
    title: 'Send formal quote for Deep Clean',
    dueDate: '2026-09-02',
    completed: false,
    notes: 'Mention 10% first-time discount if booked before Friday.',
    channel: 'email',
  },
  {
    id: 'fol-2',
    customerId: 'cust-2',
    title: 'Check if extra carpet clean needed before AGM',
    dueDate: '2026-09-05',
    completed: false,
    notes: 'David mentioned partner meeting on the 10th.',
    channel: 'phone',
  },
  {
    id: 'fol-3',
    customerId: 'cust-1',
    title: 'Monthly re-booking confirmation for October',
    dueDate: '2026-09-15',
    completed: false,
    notes: 'Confirm schedule for bank holiday weekend.',
    channel: 'meeting',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    customerId: 'cust-4',
    jobId: 'job-4',
    amount: 320,
    status: 'paid',
    dueDate: '2026-08-30',
    paidDate: '2026-08-30',
    invoiceNumber: 'INV-2026-089',
  },
  {
    id: 'pay-2',
    customerId: 'cust-1',
    jobId: 'job-1',
    amount: 140,
    status: 'pending',
    dueDate: '2026-09-05',
    invoiceNumber: 'INV-2026-092',
  },
  {
    id: 'pay-3',
    customerId: 'cust-2',
    jobId: 'job-2',
    amount: 195,
    status: 'overdue',
    dueDate: '2026-08-25',
    invoiceNumber: 'INV-2026-078',
  },
];
